### ISSUE TITLE
Long blocking task "Decompiling proto from descriptor"

### ISSUE THREAD

**Issue by BorzdeG** [devkanro/intellij-protobuf-plugin#119]
Every time you open a project, the IDE "hangs" up to 20 seconds at the "Decompiling proto from descriptor" stage.

**Comment by devkanro** [comment]
There are an option in setting page which you can disable the proto decompiling.

<img width="426" alt="截屏2022-07-29 下午2 52 22" src="https://user-images.githubusercontent.com/9367842/181700617-4a764454-73e0-4523-9453-8d57675fa457.png">

**Comment by devkanro** [comment]
And I am try to finding the way to make decompiling step to be async.

But it might be difficult, because the decompiled proto file also can provide the symbol for import and using, I need decompile them and index them before you start writing protos.

I designed this feature for go project which not included src proto, bu now it seems that the performance issues it brings outweigh its benefits.

Maybe I can remove this feature?

**Comment by BorzdeG** [comment]
I would suggest not deleting it, but turning it off by default - whoever needs it will turn it on himself.

**Comment by devkanro** [comment]
The auto-decompile option will be disabled as default after 1.6.22
